[build]
command = "chmod +x build.sh && ./build.sh"
output_directory = "out"

[build.environment]
NODE_VERSION = "18"
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"
NPM_FLAGS = "--no-audit --no-fund"

[build.processing]
skip_processing = true
